from typing import Any, Dict


# Fields that are allowed to appear in MongoDB queries
ALLOWED_FIELDS = {
    "transaction_id",
    "user_id",
    "amount",
    "currency",
    "status",
    "merchant",
    "payment_method",
    "timestamp",
    "error_message",
}


# Only these top-level keys are allowed in the LLM output
ALLOWED_TOP_LEVEL_KEYS = {
    "filter",
    "projection",
    "sort",
    "limit",
}


# Explicitly forbidden MongoDB operators
DISALLOWED_OPERATORS = {
    "$where",
    "$expr",
    "$function",
    "$lookup",
    "$regex",
}


def _check_dict(obj: Dict[str, Any]):
    """
    Recursively inspect a MongoDB query structure
    and block unsafe operators.
    """
    for key, value in obj.items():
        if key in DISALLOWED_OPERATORS:
            raise ValueError(f"Unsafe operator detected: {key}")

        if isinstance(value, dict):
            _check_dict(value)

        elif isinstance(value, list):
            for item in value:
                if isinstance(item, dict):
                    _check_dict(item)


def validate(query: Dict[str, Any]):
    """
    Validate the structure and safety of a MongoDB query
    generated by the LLM.
    """
    if not isinstance(query, dict):
        raise ValueError("Generated query must be a JSON object")

    # 1. Validate top-level structure
    for key in query.keys():
        if key not in ALLOWED_TOP_LEVEL_KEYS:
            raise ValueError(f"Unsafe top-level key detected: {key}")

    # 2. Validate filter fields (if present)
    mongo_filter = query.get("filter", {})
    if isinstance(mongo_filter, dict):
        for field in mongo_filter.keys():
            if field.startswith("$"):
                continue  # operators handled separately
            if field not in ALLOWED_FIELDS:
                raise ValueError(f"Unsafe field detected: {field}")

    # 3. Deep scan for unsafe operators
    _check_dict(query)
